name: Starter
type: Site
description: A simple template with just the basics. Bring your own design, and build what you need.
recipes:
  - core/recipes/administrator_role
  - core/recipes/core_recommended_maintenance
  - core/recipes/core_recommended_performance
  - core/recipes/document_media_type
  - drupal_cms_admin_ui
  - drupal_cms_anti_spam
  - drupal_cms_authentication
  - drupal_cms_privacy_basic
  - drupal_cms_remote_video
  - drupal_cms_seo_basic
  - easy_email_express
install:
  - menu_link_content
  - mercury
  - project_browser
  # The rest of these are in Standard.
  - inline_form_errors
  - config
  - views_ui
config:
  actions:
    system.site:
      simpleConfigUpdate:
        page.404: '/404'
    system.theme:
      simpleConfigUpdate:
        default: mercury
    project_browser.admin_settings:
      simpleConfigUpdate:
        enabled_sources:
          recommended:
            # @see recommended.yml
            uri: 'https://git.drupalcode.org/api/v4/projects/167158/repository/files/recommended.yml/raw?ref=HEAD'
            ttl: 1
          drupalorg_jsonapi: []
        default_source: recommended
    # Show the Name field in Document media forms, so it can be modified. This
    # works around core's `document_media_type` recipe, which omits the field.
    core.entity_form_display.media.document.*:
      setComponent:
        name: name
        options:
          type: string_textfield
          weight: -1
          region: content
extra:
  recipe_installer_kit:
    finish_url: '/admin/dashboard/welcome'
